/* Main.ino file generated by New Project wizard
 *
 * Created: sam. mai 3 2025
 * Processor: Arduino Uno
 * Compiler: Arduino AVR (Proteus)
 */

#pragma GCC push_options
#pragma GCC optimize("O1")

#include <Wire.h>

const int ledPin = 13; // LED connected to pin 13

void setup() {
  Wire.begin(8);                // Initialize as slave #8
  Wire.onReceive(receiveEvent); // Register receive event
  Serial.begin(9600);           // Start serial for debugging
  pinMode(ledPin, OUTPUT);
  digitalWrite(ledPin, LOW);    // Initially turn off the LED
  Serial.println("I2C Slave Ready");
}

void loop() {
  // Nothing to do here - everything happens in the receiveEvent function
  delay(100);
}

// Function that executes whenever data is received from master
void receiveEvent(int howMany) {
  while (Wire.available()) {
    char c = Wire.read(); // Receive byte as a character
    Serial.print("Received: ");
    Serial.println(c);
    
    if (c == 1) {
      Serial.println("Turning LED ON");
      digitalWrite(ledPin, HIGH);
    } else {
      Serial.println("Turning LED OFF");
      digitalWrite(ledPin, LOW);
    }
  }
}

#pragma GCC pop_options