/* Main.ino file generated by New Project wizard
 *
 * Created: sam. mai 3 2025
 * Processor: Arduino Uno
 * Compiler: Arduino AVR (Proteus)
 */

#pragma GCC push_options
#pragma GCC optimize("O1")

#include <Wire.h>

const int buttonPin = 5; // Pushbutton connected to pin 5
int buttonState = 0;     // Current state of the button
int lastButtonState = 0; // Previous state of the button

void setup() {
  Wire.begin();        // Initialize as master
  Serial.begin(9600);  // Start serial for debugging
  pinMode(buttonPin, INPUT_PULLUP); // Set button pin as input with pull-up
  Serial.println("I2C Master Ready");
}

void loop() {
  // Read the state of the pushbutton (inverted due to pull-up)
  buttonState = !digitalRead(buttonPin);
  
  // Check if button state has changed
  if (buttonState != lastButtonState) {
    // If button is pressed (HIGH)
    if (buttonState == HIGH) {
      Serial.println("Button pressed - sending ON command");
      Wire.beginTransmission(8); // Transmit to device #8
      Wire.write(1);             // Send value 1 to turn LED ON
      Wire.endTransmission();    // Stop transmitting
    } else {
      Serial.println("Button released - sending OFF command");
      Wire.beginTransmission(8); // Transmit to device #8
      Wire.write(0);             // Send value 0 to turn LED OFF
      Wire.endTransmission();    // Stop transmitting
    }
    
    // Update the last button state
    lastButtonState = buttonState;
    
    // Small delay to prevent bouncing
    delay(50);
  }
}

#pragma GCC pop_options